schema_version = "1.0.0"
id = "BRVLayers"
name = "Batch Render View Layers"
version = "1.2.2"
tagline = "Batch Render View Layers"
maintainer = "KIN"
support = "https://github.com/chenkin123/Batch_Render_View_Layers"
type = "add-on"
tags = ["tags"]
blender_version = "4.5.0"
blender_version_min = "4.3.0"
category = "Render"
license = ["SPDX:GPL-3.0-or-later",]





